### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by GewelsJI** [uzh-rpg/svit#6]
Hey, authors,

Thanks for your open sourcing such a nice work. I have a small question on your code:

Why [F.gumbel_softmax](https://github.com/uzh-rpg/svit/blob/d2472c13e667f4ef4c098898faec2e6cbe6c8e01/classification/selective_vit.py#L65) during training, but [torch.argmin](https://github.com/uzh-rpg/svit/blob/d2472c13e667f4ef4c098898faec2e6cbe6c8e01/classification/selective_vit.py#L67) during inference?

Hope to receive your response. :)

Best,
Daniel.

**Comment by kaikai23** [comment]
During training you need to have some random behavior so that when the mask probability is less than 0.5, the mask can still sometimes be True(or 1). During inference it is preferred to have deterministic predictions, so > 0.5 probability produce a True mask, otherwise a False mask.

You can actually use F.gumbel_softmax at inference time as well, with no noticeable impact on accuracy.

**Comment by GewelsJI** [comment]
Thanks for your quick reply. That's great.

Best,
Daniel.

**Comment by King4819** [comment]
> During training you need to have some random behavior so that when the mask probability is less than 0.5, the mask can still sometimes be True(or 1). During inference it is preferred to have deterministic predictions, so > 0.5 probability produce a True mask, otherwise a False mask.
> 
> 
> 
> You can actually use F.gumbel_softmax at inference time as well, with no noticeable impact on accuracy.

I want to ask that why using argmin instead of argmax ? I think the mask true should correspond to larger probability, so it should use argmax ?

Hope to get your response, thanks!

**Comment by King4819** [comment]
@kaikai23 Hi, I want to ask that in my experiment, if using argmin at inference stage, the number of keep tokens at ViT final layer will be zero, do you have any suggestion ? Hopes to get your reply, thanks !!!
