### ISSUE TITLE
Attention type in code

### ISSUE THREAD

**Issue by King4819** [uzh-rpg/svit#7]
Hi, I want to ask that whether the code implement global attention or deformable attention.

Since I want to calculate the FLOPs drop ratio according to the number of tokens that each ViT layer used, and the FLOPs of deformable attention is proportional to the number of tokens? O(N) ?

Thank you very much!

**Comment by kaikai23** [comment]
Hi, 

In terms of classification code, we used only global attention, which is applied on all the remaining tokens after pruning. You can easily write flops as a function of # of tokens, by replacing the '197' by the actual # of tokens in a vit layer, please refer to the [calculations here](https://github.com/uzh-rpg/svit/assets/71677542/1d84d78c-2234-492c-9216-2a02f3d87cd4).

For deformable attention in the detection code, I guess it is difficult to find a tool to calculate the flops since cuda implementation is involved. I just avoided calculating the flops there and reported the speed instead (frames per second).

**Comment by King4819** [comment]
Thanks for your reply !!!
